### ISSUE TITLE
conda package installs into `python3.1/site-packages`

### ISSUE THREAD

**Issue by asottile** [python/tzdata#44]
I don't know if the bug is for this, but it's somehow breaking pre-commit's tests for conda.

I'm installing `python-tzdata` there and then importing the `tzdata` module and getting an import error:

```console
$ CONDA_PREFIX=conda-default conda list
# packages in environment at conda-default:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.9.30            h06a4308_1  
certifi                   2021.5.30       py310h06a4308_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0              h1d223b6_10    conda-forge
libgomp                   11.2.0              h1d223b6_10    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuuid                   1.0.3                h7f8727e_2  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1l               h7f8727e_0  
pip                       21.2.4          py310h06a4308_0  
python                    3.10.0               h12debd9_1  
python-tzdata             2021.1             pyhd3eb1b0_0  
readline                  8.1                  h27cfd23_0  
setuptools                58.0.4          py310h06a4308_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.11               h1ccaba5_0  
tzdata                    2021a                h5d7bf9c_0  
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

```console
$ find conda-default/ -name tzdata
conda-default/lib/python3.1/site-packages/tzdata
```

I admittedly don't know much about conda -- I believe the environment is created from this `environment.yml` and then it runs `conda install python-tzdata`:

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  # This cannot be empty as otherwise no environment will be created.
  # We're using openssl here as it is available on all system and will
  # most likely be always installed anyways.
  # See https://github.com/conda/conda/issues/9487
  - openssl
```
